### PR TITLE
Fix: Exit screen cleanup & Enter screen cleanup & Fixed #13

### LINKED ISSUE #13: [BUG ]  Error Messages not unwrapped
**Describe the bug**
Error messages are not unwrapped

**To Reproduce**
1. Clone a repo using templa-rs 
2. re-clone using the same name
3. You will find the error "Error Encountered while cloning, Ok("fatal: destination path 'new_proj' already exists and is not an empty directory.\n")"

**Expected behavior**
Error should be unwrapped into stderr like:

```fatal: destination path 'new_proj' already exists and is not an empty directory.```

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: All Platforms

### PR DESCRIPTION
**Pull request by sanjaybaskaran01**
Fixed q key where it now exits the alternate screen (added alternate screen for the purpose of TUI) and enter key clears up the TUI screen as well and prints Cloning message. 
(also refactored command.rs to return the output and not handle any TUI commands)

### CODE REVIEW

File: src/tui.rs [hunk 1]
```diff
@@ -109,7 +110,23 @@ pub fn render_tui(key:String, proj_name: &str){
...
+                            LeaveAlternateScreen,
+                        ).unwrap();
+                    println!("\nCloning {}..\n", proj_name);
+                    let output = command::git_clone(proj_name, selected_template.url.to_string());
+                    terminal.show_cursor().unwrap();
+                    if output.status.success() {
+                            println!("\nCloned {} successfully\n", &proj_name);
+                        } else {
+                            println!(
+                                "\nError Encountered while cloning, {:?}",
```
Comment (Mannan-Goyal) [inline src/tui.rs:126]: Can you print the error string by unwrapping output instead of printing using the debug flag?

**Review by Mannan-Goyal — CHANGES_REQUESTED** [review]
Please see the comments

File: src/tui.rs (hunk 1 above)
Comment (sanjaybaskaran01) [reply src/tui.rs]: Opened issue & Fixed #13

Comment (mintbomb27) [reply src/tui.rs]: Resolved!

**Comment by Mannan-Goyal** [comment]
Hey, @sanjaybaskaran01 congratulations on getting the first PR merged, we would like to give you a shoutout on our twitter account twitter.com/ieeevitvellore. Can you please provide us with your twitter handle?

**Comment by sanjaybaskaran01** [comment]
Hey @Mannan-Goyal, this is a very promising project that you guys have here 😄! , it was fun contributing. My twitter handle is twitter.com/sanjayybaskaran
